In [2]:
import torch
import numpy as np

In [5]:
#创建一个张量
tensor_a = torch.tensor([[1,2],[3,4]],dtype=torch.float32)
print(tensor_a)
print(tensor_a.numpy())
tensor_b = np.array([[5,6],[7,8]],dtype='float32')
tensor_b = torch.from_numpy(tensor_b)
print(tensor_b)

tensor([[1., 2.],
        [3., 4.]])
[[1. 2.]
 [3. 4.]]
tensor([[5., 6.],
        [7., 8.]])


In [6]:
zeros_tensor = torch.zeros([2,4],dtype=torch.float32)
print(zeros_tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [11]:
print('before modify:',tensor_a)
tensor_a[0][0] = torch.tensor([6])
print('after modify:',tensor_a)

before modify: tensor([[5., 5.],
        [3., 4.]])
after modify: tensor([[6., 5.],
        [3., 4.]])


In [14]:
x = torch.tensor([1])
print(x)
x1 = x.item()
print(x1)

tensor([1])
1


In [32]:
x = torch.tensor([[1.,-1.],[1.,1.]],dtype=torch.float32,requires_grad=True)
y = torch.tensor([[1.,-1.],[1.,1.]],dtype=torch.float32,requires_grad=True)
z = (x.pow(2)+ y.pow(3)).sum() # x^2 + y^3 的导数
z.backward()
print('x的导数:',x.grad)
print('y的导数:',y.grad)


x的导数: tensor([[ 2., -2.],
        [ 2.,  2.]])
y的导数: tensor([[3., 3.],
        [3., 3.]])


In [34]:
x = torch.tensor([[1.,-1.],[1.,1.]],dtype=torch.float32,requires_grad=True)
y = torch.tensor([[2.,-2.],[2.,2.]],dtype=torch.float32,requires_grad=True)
z = torch.add(x,y)
print('torch.add(x,y)：',z)
z = y.add(x,alpha=2)
print('y.add(x):',z)

torch.add(x,y)： tensor([[ 3., -3.],
        [ 3.,  3.]], grad_fn=<AddBackward0>)
y.add(x): tensor([[ 4., -4.],
        [ 4.,  4.]], grad_fn=<AddBackward0>)


In [35]:
x = torch.tensor([[1.,-1.],[1.,1.]],dtype=torch.float32,requires_grad=True)
y = torch.tensor([[2.,-2.],[2.,2.]],dtype=torch.float32,requires_grad=True)
z = torch.sub(x,y)
print('torch.add(x,y)：',z)
z = y.sub(x,alpha=2)
print('y.add(x):',z)

torch.add(x,y)： tensor([[-1.,  1.],
        [-1., -1.]], grad_fn=<SubBackward0>)
y.add(x): tensor([[0., 0.],
        [0., 0.]], grad_fn=<SubBackward0>)


In [42]:
x = torch.randn(4,4)
print(x)
x = x.reshape(2,8)
print(x)

tensor([[ 0.5297,  0.2418, -0.5601,  1.0870],
        [-0.5980,  0.9345,  0.2566,  0.8302],
        [ 2.3981,  1.5153, -0.3917,  0.3148],
        [-1.0985,  0.5163, -1.3804, -1.0378]])
tensor([[ 0.5297,  0.2418, -0.5601,  1.0870, -0.5980,  0.9345,  0.2566,  0.8302],
        [ 2.3981,  1.5153, -0.3917,  0.3148, -1.0985,  0.5163, -1.3804, -1.0378]])


In [47]:
x = torch.randn(2,2,4)
y = torch.randn(2,2,4)
reduce_mean = torch.mean(((x - y)**2).sum())
print('x:',x)
print('y:',y)
print('reduce_mean:',reduce_mean)

x: tensor([[[ 0.1611, -0.2936,  0.0684,  2.0824],
         [ 1.9325,  1.5520, -0.6921, -0.5396]],

        [[ 2.0934,  0.3382, -0.3702, -1.4100],
         [-0.8347,  0.9150,  1.9065, -0.6693]]])
y: tensor([[[-0.2307, -0.2435, -0.6239, -0.2596],
         [-0.3924, -0.5992,  0.5582,  1.6862]],

        [[-1.4488,  0.2442, -0.4640,  0.5149],
         [ 0.5927, -0.2686, -0.6326, -0.2007]]])
reduce_mean: tensor(49.0464)


In [38]:
y = torch.argmax(x)
print('最大的值：',y.item())

最大的值： 6
